config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  scope '(:locale)', locale: /fr|es|de|it|zh-CN|ja|pt|ko|el|ru|th/ do

    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update] do
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
      resources :meals, only: [:index, :show, :new, :create, :edit, :update, :destroy ] do

        resources :meal_tags
      end
    end
    resources :reviews, only: [ :show, :edit, :update, :destroy ]
    resources :tags, only: [:index]
    namespace :owners do
      resources :restaurants
    end

    get "/tags/save-with-session", to: "tags#save_with_session"
  end
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo_.png", alt: "logo" %>
  <% end %>

  <%= image_tag ApplicationRecord::FLAGS[I18n.locale], alt: "locale", width: 40 %>


  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="menu"> <%= t('.menu') %></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if current_page?(restaurants_path) %>
          <li>- <a class="nav-item" type="button" data-toggle="modal" data-target="#FoodModal" class="tab-underlined" id="food"><%=t('.food')%></a>
          </li>
          <li>- <a href="tags" class="nav-item ">
            <%= t('.allergy') %></a>
          </li>
        <% elsif !current_page?(root_path) %>
          <li class="nav-item">
            <%= link_to t('.lang'), root_path, class: "nav-item" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to t('.out'), destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  <% else %>
  <%= link_to "Login", new_user_session_path, class: "nav-link btn-chief" %>
  <% end %>
</div>