config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  scope '(:locale)', locale: /fr|es|de|it|zh-CN|ja|pt|ko|el|ru|th/ do

    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update] do
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
      resources :meals, only: [:index, :show, :new, :create, :edit, :update, :destroy ] do

        resources :meal_tags
      end
    end
    resources :reviews, only: [ :show, :edit, :update, :destroy ]
    resources :tags, only: [:index]
    namespace :owners do
      resources :restaurants
    end

    get "/tags/save-with-session", to: "tags#save_with_session"
  end
end

app/views/pages/home.html.erb
<div class="background">
    <div class="">
        <div class="flags px-3">
            <div class="row">
                <div class="col-3 p-3">
                    <a href="/tags" class="country_flags">
                        <%= image_tag "united-kingdom.png", alt: "united-kingdom", width: 55%></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/fr/tags" class="country_flags">
                        <%= image_tag "france.png", alt: "france", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/de/tags" class="country_flags">
                        <%= image_tag "germany.png", alt: "germany", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/it/tags" class="country_flags">
                        <%= image_tag "italy.png", alt: "italy", width: 55 %></a>
                </div><br>
                <div class="col-3 p-3">
                    <a href="/ja/tags" class="country_flags">
                        <%= image_tag "japan.png", alt: "japan", width: 55 %></a> <br>
                </div>
                <div class="col-3 p-3">
                    <a href="/pt/tags" class="country_flags">
                        <%= image_tag "portugal.png", alt: "portugal", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/ko/tags" class="country_flags">
                        <%= image_tag "south-korea.png", alt: "south-korea", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/es/tags" class="country_flags">
                        <%= image_tag "spain.png", alt: "spain", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/zh-CN/tags" class="country_flags">
                        <%= image_tag "china.png", alt: "china", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/el/tags" class="country_flags">
                        <%= image_tag "greece.png", alt: "greece", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/th/tags" class="country_flags">
                        <%= image_tag "thailand.png", alt: "thailand", width: 55 %></a>
                </div>
                <div class="col-3 p-3">
                    <a href="/ru/tags" class="country_flags">
                        <%= image_tag "russia.png", alt: "russie", width: 55 %></a>
                </div>
            </div>
        </div>
        <div class="def-wimp">
            <p>* See all restaurants informations in your language *</p>
        </div>
      <% if user_signed_in? %>
        <%= link_to t('.create'), new_restaurant_path, class: "btn-review" %>
      <% end %>
    </div>
</div>