config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  scope '(:locale)', locale: /fr|es|de|it|zh-CN|ja|pt|ko|el|ru|th/ do

    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update] do
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
      resources :meals, only: [:index, :show, :new, :create, :edit, :update, :destroy ] do

        resources :meal_tags
      end
    end
    resources :reviews, only: [ :show, :edit, :update, :destroy ]
    resources :tags, only: [:index]
    namespace :owners do
      resources :restaurants
    end

    get "/tags/save-with-session", to: "tags#save_with_session"
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :meal_tags, dependent: :destroy
  enum status: { allergy: 0, category: 1 }
  translates :title
  after_create :translates_with_api

  def translates_with_api
    translator = TranslateApiService.new
    Tag::LOCALES.select { |l| l != I18n.locale }.each do |l|
      translate_title = translator.call(text: self.title, local: I18n.locale, target: l)
      self.attributes = { title: translate_title, locale: l }
      self.save
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :save_with_session]
  def index
    @tags = Tag.all
  end

  def save_with_session
    session[:tag_ids] = params[:tags_session][:tags][1..-1]
    redirect_to restaurants_path
  end
end

app/views/tags/index.html.erb
<div class="container">
    <%= simple_form_for :tags_session, url: tags_save_with_session_path, method: :get do |f| %>
    <input name="utf8" type="hidden" value="&#x2713;" />
    <fieldset class="form-group check_boxes required tags_session_tags">
        <input type="hidden" name="tags_session[tags][]" value="" />
        <div class="funky">
            <div class="funky-warning">
              <h2 class="text-center"><%= t('.allergi') %> </h2>
              <% tags = Tag.where(status: :allergy) %>
                <% tags.each_with_index do |tag| %>
                <div class="form-check form-check-inline box-size">
                    <input class="form-check-input check_boxes required" type="checkbox" value="<%= tag.id %>" name="tags_session[tags][]" id="tags_session_tags_<%= tag.id %>" />
                    <label class="collection_check_boxes" for="tags_session_tags_<%= tag.id %>">
                        <%= tag.title %></label>
                </div>
                <% end %>
                 <% tags2 = Tag.where(status: :category) %>
                 <h2 class="text-center"><%= t('.food') %> </h2>
                <% tags2.each_with_index do |tag| %>
                <div class="form-check form-check-inline box-size">
                    <input class="form-check-input check_boxes required" type="checkbox" value="<%= tag.id %>" name="tags_session[tags][]" id="tags_session_tags_<%= tag.id %>" />
                    <label class="collection_check_boxes" for="tags_session_tags_<%= tag.id %>">
                        <%= tag.title %></label>
                </div>
                <% end %>
            </div>
        </div>
</div>
</fieldset>
  <div class="btn-review "><%= f.button :submit, t('.valid') %></div>
  <div class=" button2 " id="skip">
    <%= link_to t('.skip'), restaurants_path, method: :get, class: "button2" %>
</div>

<% end %>