config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  scope '(:locale)', locale: /fr|es|de|it|zh-CN|ja|pt|ko|el|ru|th/ do

    resources :restaurants, only: [:index, :show, :new, :create, :edit, :update] do
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
      resources :meals, only: [:index, :show, :new, :create, :edit, :update, :destroy ] do

        resources :meal_tags
      end
    end
    resources :reviews, only: [ :show, :edit, :update, :destroy ]
    resources :tags, only: [:index]
    namespace :owners do
      resources :restaurants
    end

    get "/tags/save-with-session", to: "tags#save_with_session"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :meals, dependent: :destroy
  has_many :reviews, dependent: :destroy
  enum food_style: { french: 0, italian: 1, japanese: 2, chinese: 3, pubs: 4, others: 5 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  translates :story
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :address, presence: true, uniqueness: true
  validates :story, presence: true
  after_create :translates_with_api

  def translates_with_api
    translator = TranslateApiService.new
    Restaurant::LOCALES.select { |l| l != I18n.locale }.each do |l|
      translate_story = translator.call(text: self.story, local: I18n.locale, target: l)
      self.attributes = { story: translate_story, locale: l }
      self.save
    end
  end
end

app/controllers/owner/restaurants.rb
class Owner::RestaurantsController < ApplicationController
  def index
  end

  def show
    @restaurants = Restaurant.where(user: current_user)
    @restaurants
  end

  def new
    @current_user = Restaurant.where(user: current_user)
    @restaurant = Restaurant.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/owners/restaurants_controller.rb
class Owners::RestaurantsController < ApplicationController

  def new
    @current_user = Restaurant.where(user: current_user)
    @restaurant = Restaurant.new
  end

  def create
    @current_user = Restaurant.where(user: current_user)
    @restaurant = Restaurant.new
  end

  def edit
  end

  def update
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
      redirect_to restaurants_path
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:restaurants_index]
      @restaurants = Restaurant.where(food_style: params[:restaurants_index][:restaurants])
    else
      @restaurants = Restaurant.all
    end
    @restaurants_geo = Restaurant.geocoded

    @markers = @restaurants_geo.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant }),
        image_url: helpers.asset_url('chef.png')
      }
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @meals = Meal.where(restaurant: @restaurant)

    @markers = [{
      lat: @restaurant.latitude,
      lng: @restaurant.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { restaurant: @restaurant }),
      image_url: helpers.asset_url('resto.jpg')
    }]
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(resto_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(resto_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def resto_params
    params.require(:restaurant).permit(:name, :address, :story, :photo, :food_style)
  end
end

app/views/restaurants/_info_window.html.erb
<%= link_to restaurant_path(restaurant) do %>
  <%= cl_image_tag restaurant.photo, height: 100, width: 100, crop: :fill %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
  <p> <%= restaurant.food_style %> </p>
<% end %>

app/views/restaurants/edit.html.erb
<%= simple_form_for @restaurant do |f| %>
  <div class="container fluid">

    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :food_style, collection: Restaurant.food_styles.keys %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <%= f.submit class: "btn btn-review"%>
<% end %>

app/views/restaurants/index.html.erb
<div class="restaurant">
    <div class="stick-me awsome col-2" id="map-button">
        <i class="fas fa-arrow-alt-circle-left "></i>
        <p>Map</p>
    </div>

    <div class="modal fade" id="FoodModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        <%= t('.choose') %>
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="toggle-container">
                        <fieldset class="form-group check_boxes required restaurants_food_styles">
                            <%= simple_form_for :restaurant_index, url: restaurants_path, method: :get do |f| %>
                            <input name="utf8" type="hidden" value="&#x2713;" />
                            <input type="hidden" value="" />
                            <% restaurants = Restaurant.where(food_style: :french) %>
                            <% restaurants.food_styles.keys.each do |food_style| %>
                            <div class="form-check form-check-inline box-size">
                                <input type="checkbox" value="<%= food_style %>" name="restaurants_index[restaurants][]" id="restaurants_index_restaurants_<%= food_style %>" />
                                <label class="collection_check_boxes" for="restaurants_index_restaurants_<%= food_style %>">
                                    <%= t(".#{food_style.downcase}") %></label>
                            </div>
                            <% end %>
                    </div>
                </div>
                <div class="modal-footer">
                    <%= f.button :submit %>
                    <button type="submit" class="btn button2"><%= t('.sub') %></button>
                    <button type="button" class="btn button2" data-dismiss="modal"><%= t('.close')%></button>
                </div>
                </fieldset>
                <% end %>
            </div>
        </div>
    </div>
</div>

<% @restaurants.each do |restaurant| %>
  <div class="rows d-flex" id="rest">
    <%= link_to restaurant_path(restaurant) do %>
      <div class="col-sm card-trip">
        <%= cl_image_tag restaurant.photo, height: 300, width: 400, crop: :fill %>
        <div class="card-trip-infos">
            <div>
                <div class="name ">
                    <%= restaurant.name %>
                </div>
                <div class="style">
                    <%= restaurant.food_style %>
                </div>
                <div class="address">
                    <%= restaurant.address %>
                </div>
            </div>
            <h2 class="card-trip-pricing"></h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div id="map" class="d-none" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  <i class="fas fa-crosshairs" id="geoloc-target"></i>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <div class="container-fluid">
  <%= f.input :name, label: t('.name') %>
  <%= f.input :address, label: t('.address') %>
  <%= f.input :story, label: t('.story') %>
  <%= f.input :food_style, collection: Restaurant.food_styles.keys %>
  <label class="w-100" id="upload-label">
  <div class="btn-review"><%= t('.pic')%></div>
  <span class="d-none">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </span>
</label>
  </div>
  <%= f.submit class: "btn-review"%>
<% end %>

app/views/restaurants/show.html.erb
<div class="banner" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.4),rgba(0,0,0,0.1)), url('<%= cl_image_path @restaurant.photo, height: 300, width: 400, crop: :fill %>');">
  <div class="container">
    <h1>
      <%= @restaurant.name %>
    </h1>
  </div>
</div>

<div class="restaurant">
  <div class="description">
    <%= link_to "X", restaurants_path, class: "btn btn-back"%>
    <h3>
        <%= t('.descr') %>
    </h3>
    <p><%= @restaurant.story %> </p>
  </div>
  <% if current_user == @restaurant.user %>
    <div class="d-flex">
      <%= link_to t('.add'), new_restaurant_meal_path(@restaurant), class: "btn btn-review" %>
    </div>
  <% end %>
</div>

<!-- menu -->
<div class="menu">
  <!-- starter -->
  <div class="starter">
    <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      <h1><%= t('.start') %> +</h1>
    </a>
    <div class="collapse" id="collapseExample">
      <div class="cards ">
        <% @restaurant.meals.each do |meal| %>
          <% if meal.course == 'Starter' %>
            <% if meal.photo.present? %>
              <div class="card-category" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.1)), url('<%= cl_image_path meal.photo, height: 300, width: 400, crop: :fill %>');">
            <% else %>
              <div class="card-category" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.1)), url(<%= image_path "default_meal.png" %>);">
            <% end %>
            <button type="button" class="btn btn-ghost" data-toggle="modal" data-target="#modal-<%= meal.id %>">
              <%= meal.name %>
            </button></div>
            <div class="modal fade" id="modal-<%= meal.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <!-- header -->
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                      <%= meal.name %> -
                      <%= meal.price %> €
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <!-- body -->
                  <div class="modal-body">
                    <%= cl_image_tag meal.photo, height: 300, width: 300, crop: :fill %>
                    <br><br>
                    <%= meal.description %>
                    <br><br>
                    <!-- tags -->
                    <div class="meals-tag">
                      <% meal.meal_tags.each do |meal_tag| %>
                        <% if meal_tag.tag.status == "allergy" %>
                          <div class="allergy"> - <%=meal_tag.tag.title%> </div>
                        <% else %>
                          <div class="pref"> - <%=meal_tag.tag.title%></div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <!-- footer -->
                  <div class="modal-footer">
                    <% if current_user == @restaurant.user %>
                      <%= link_to t('.edit'), edit_restaurant_meal_path(@restaurant, meal), class: 'btn-delete' %>
                      <%= link_to t('.remove'), restaurant_meal_path(@restaurant, meal), class: "btn-review",
                      method: :delete,
                      data: { confirm: t('.conf') } %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- main course -->
  <div class="main-course">
    <a data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample2">
      <h1><%= t('.main') %> +</h1>
    </a>
    <div class="collapse" id="collapseExample2">
      <div class="cards ">
        <% @restaurant.meals.each do |meal| %>
          <% if meal.course == 'Main' %>
            <% if meal.photo.present? %>
              <div class="card-category" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.1)), url('<%= cl_image_path meal.photo, height: 300, width: 400, crop: :fill %>');">
            <% else %>
              <div class="card-category" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.1)), url(<%= image_path "default_meal.png" %>);">
            <% end %>
            <button type="button" class="btn btn-ghost " data-toggle="modal" data-target="#modal-<%= meal.id %>">
              <%= meal.name %>
            </button></div>
            <div class="modal fade" id="modal-<%= meal.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <!-- header -->
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                      <div class="modal-name">
                        <%= meal.name %>
                      </div>   -
                      <div class="modal-price">
                        <%= meal.price %> €
                      </div>
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <!-- body -->
                  <div class="modal-body">
                    <%= cl_image_tag meal.photo, height: 300, width: 400, crop: :fill %>
                    <br><br>
                    <%= meal.description %>
                    <br><br>
                    <!-- tags -->
                    <div class="meals-tag">
                      <% meal.meal_tags.each do |meal_tag| %>
                        <% if meal_tag.tag.status == "allergy" %>
                          <div class="allergy"> - <%=meal_tag.tag.title%> </div>
                        <% else %>
                          <div class="pref"> - <%=meal_tag.tag.title%></div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <!-- footer -->
                  <div class="modal-footer">
                    <% if current_user == @restaurant.user %>
                      <%= link_to t('.edit'), edit_restaurant_meal_path(@restaurant, meal), class: 'btn-review' %>
                      <%= link_to t('.remove'), restaurant_meal_path(@restaurant, meal), class: "btn-delete",
                      method: :delete,
                      data: { confirm: t('.conf') } %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- dessert -->
  <div class="dessert">
    <a data-toggle="collapse" href="#collapseExample3" role="button" aria-expanded="false" aria-controls="collapseExample3">
      <h1><%= t('.dess') %> +</h1>
    </a>
    <div class="collapse" id="collapseExample3">
      <div class="cards ">
        <% @restaurant.meals.each do |meal| %>
          <% if meal.course == 'Dessert' %>
            <% if meal.photo.present? %>
              <div class="card-category" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.1)), url('<%= cl_image_path meal.photo, height: 300, width: 400, crop: :fill %>');">
            <% else %>
              <div class="card-category" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.3), rgba(0,0,0,0.1)), url(<%= image_path "default_meal.png" %>);">
            <% end %>
            <button type="button" class="btn btn-ghost" data-toggle="modal" data-target="#modal-<%= meal.id %>">
                <%= meal.name %>
            </button></div>
            <div class="modal fade" id="modal-<%= meal.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel3" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <!-- header -->
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                      <%= meal.name %> -
                      <%= meal.price %> €
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <!-- body -->
                  <div class="modal-body">
                    <%= cl_image_tag meal.photo, height: 300, width: 400, crop: :fill %>
                    <%= meal.description %>
                    <!-- tags -->
                    <div class="meals-tag">
                      <% meal.meal_tags.each do |meal_tag| %>
                        <% if meal_tag.tag.status == "allergy" %>
                          <div class="allergy"> <%=meal_tag.tag.title%> </div>
                        <% else %>
                          <div class="pref"><%=meal_tag.tag.title%></div>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                  <!-- footer -->
                  <div class="modal-footer">
                    <% if current_user == @restaurant.user %>
                      <%= link_to t('.edit'), edit_restaurant_meal_path(@restaurant, meal), class: 'btn btn-delete' %>
                      <%= link_to t('.remove'), restaurant_meal_path(@restaurant, meal), class: "btn btn-review",
                      method: :delete,
                      data: { confirm: t('.conf') } %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br>
 <!-- map -->
<div id="map2" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<br>

<!-- reviews -->
<%= link_to t('.review'), new_restaurant_review_path(@restaurant.id), class: "btn btn-review" %>
<ul class="reviews">
  <% @restaurant.reviews.each do |review| %>
  <div class="card-review">
    <li class="title-review"><%= review.user.nickname %></li>
    <li class="contt-review"><%= review.content %></li>
    <% if current_user == review.user %>
      <div class="d-flex rows">
        <div class="col-5 pl-8">
          <%= link_to t('.editcomment'), edit_restaurant_review_path(@restaurant, review), class: "btn btn-review" %>
        </div>
        <div class="col-5 pl-8">
          <%= link_to t('.removecomment'), restaurant_review_path(@restaurant, review), class: "btn btn-review",
              method: :delete,
              data: { confirm: t('.conf') } %>
        </div>
      </div>
    <% end %>
    <li class="sep-review">-------------------------------------</li>
  </div>
  <% end %>
</ul>
<br>

<!-- delete restaurant -->
<% if current_user == @restaurant.user %>
  <div class="d-flex">
    <%= link_to t('.editresto'), edit_restaurant_path(@restaurant), class: 'btn btn-review' %>
    <%= link_to t('.del'), owners_restaurant_path(@restaurant), class: "btn btn-delete", method: :delete, data: { confirm: t('.rem') } %>
  </div>
<% end %>